// Synthetic official CLI-shaped response. No network requests in this fixture.
export function measurement() {
  const probe = {
    continent: 'AS',
    region: 'Eastern Asia',
    country: 'CN',
    state: null,
    city: 'Shanghai',
    asn: 45090,
    network: 'Tencent',
    latitude: 31.23,
    longitude: 121.47,
    tags: ['u-example', 'datacenter-network'],
    resolvers: ['private', '1.1.1.1'],
  };
  return {
    id: 'measurement-fixture',
    type: 'http',
    status: 'finished',
    target: 'sshawn9.com',
    createdAt: '2026-09-18T15:23:18.000Z',
    updatedAt: '2026-09-18T15:23:19.000Z',
    probesCount: 3,
    limit: 3,
    timeout: 10,
    locations: [{ magic: 'China+Shanghai' }],
    measurementOptions: {
      protocol: 'HTTPS',
      port: 443,
      ipVersion: 4,
      resolver: '1.1.1.1',
      request: {
        host: 'sshawn9.com',
        path: '/zh/',
        query: '',
        method: 'GET',
        headers: { 'X-Test': 'one' },
      },
    },
    results: [
      {
        probe,
        result: {
          status: 'finished',
          resolvedAddress: '172.67.211.244',
          statusCode: 200,
          statusCodeName: 'OK',
          rawOutput: 'HTTP/1.1 200',
          rawHeaders: 'CF-Cache-Status: HIT\r\n',
          rawBody: '',
          truncated: true,
          headers: {
            'CF-Cache-Status': 'HIT',
            'CF-Ray': 'a3d159dda84c2669-NRT',
            'Cache-Control': ['public', 'max-age=400, must-revalidate'],
            'Server-Timing': [
              'cfCacheStatus;desc="HIT"',
              'cfEdge;dur=26,cfOrigin;dur=0,cfWorker;dur=21',
            ],
            Date: 'Fri, 18 Sep 2026 15:23:18 GMT',
            'Last-Modified': 'Sun, 06 Nov 1994 08:49:37 GMT',
            Expires: 'Sat, 19 Sep 2026 15:23:18 GMT',
            Age: '0',
            'Content-Length': '0',
            'Content-Type': 'Text/HTML; charset=UTF-8; extra="semi;comma,ok"',
            Vary: ['Accept-Encoding', 'Accept-Language'],
            'Content-Encoding': 'br',
            ETag: '"x"',
            Server: 'cloudflare',
            'X-Unknown': ['a', 'b'],
          },
          timings: { dns: null, tcp: 223, tls: 230, firstByte: 250, download: 0, total: 703 },
          tls: {
            authorized: false,
            protocol: 'TLSv1.3',
            cipherName: 'TLS_AES_256_GCM_SHA384',
            error: 'fixture verification error',
            createdAt: '2026-09-13T16:34:00Z',
            expiresAt: '2026-12-12T17:33:57Z',
            subject: {
              CN: 'sshawn9.com',
              alt: 'DNS:sshawn9.com, DNS:*.zashboard.sshawn9.com, IP Address:192.0.2.1',
            },
            issuer: { C: 'US', O: 'Google Trust Services', CN: 'WE1' },
            keyType: 'EC',
            keyBits: 256,
            serialNumber: '00:12',
            fingerprint256: 'AB:CD',
            publicKey: 'fixture-key',
          },
        },
      },
      {
        probe: { ...probe, city: 'Beijing' },
        result: { status: 'failed', failureSource: 'target', rawOutput: 'connection refused' },
      },
      {
        probe: { ...probe, city: 'Tokyo', country: 'JP' },
        result: { status: 'offline', rawOutput: 'probe disconnected' },
      },
    ],
  };
}
